# Generated by Django 4.2.4 on 2023-09-07 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('fullname', models.CharField(max_length=500)),
                ('cmt', models.TextField(max_length=5000)),
                ('date_time', models.DateTimeField()),
                ('poem_unique_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=1000)),
                ('poem_name', models.CharField(max_length=5000)),
                ('poem_description', models.TextField(max_length=1000000)),
                ('view', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('tag', models.CharField(choices=[('কিশোর', 'কিশোর'), ('রোম্যান্টিক', 'রোম্যান্টিক'), ('আঠারো উর্ধ্ব', 'আঠারো উর্ধ্ব'), ('ভালোবাসা-প্রেম', 'ভালোবাসা-প্রেম'), ('দুঃখের কবিতা', 'দুঃখের কবিতা'), ('জাগরন মূলক', 'জাগরন মূলক'), ('সমাজকেন্দ্রিক', 'সমাজকেন্দ্রিক'), ('দেশাত্মবোধক', 'দেশাত্মবোধক'), ('প্রকৃতিপ্রেম', 'প্রকৃতিপ্রেম'), ('শিশু কবিতা', 'শিশু কবিতা')], max_length=1000)),
                ('unique_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
