# Generated by Django 4.2.4 on 2023-09-07 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kobita', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
