# Generated by Django 4.2.4 on 2023-09-09 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5000)),
                ('tag', models.CharField(choices=[('রোম্যান্টিক', 'রোম্যান্টিক'), ('সামাজিক', 'সামাজিক'), ('প্রকৃতি ও মানুষ', 'প্রকৃতি ও মানুষ'), ('কাল্পনিক ও অতিপ্রাকৃত', 'কাল্পনিক ও অতিপ্রাকৃত'), ('প্রতীকধর্মী', 'প্রতীকধর্মী'), ('আঠারো উর্ধ্ব', 'আঠারো উর্ধ্ব'), ('বৈজ্ঞানিক', 'বৈজ্ঞানিক'), ('মনস্তাত্তিক', 'মনস্তাত্তিক'), ('ঐতিহাসিক', 'ঐতিহাসিক'), ('কমেডি', 'কমেডি'), ('বাস্তব', 'বাস্তব'), ('ডিটেকিভ', 'ডিটেকিভ'), ('ঘরোয়া', 'ঘরোয়া'), ('ভ্রমণ কাহিনী', 'ভ্রমণ কাহিনী'), ('শুধু গল্প', 'শুধু গল্প')], max_length=500)),
                ('description', models.TextField(max_length=500000000000000)),
                ('author', models.CharField(max_length=500)),
                ('view', models.IntegerField()),
                ('unique_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
