# Generated by Django 4.2.4 on 2023-09-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='edu_qual',
            field=models.CharField(choices=[('B.Sc', 'B.Sc'), ('B.Com', 'B.Com'), ('BBA', 'BBA'), ('HSC', 'HSC'), ('SSC', 'SSC'), ('PSC', 'PSC'), ('PSC', 'পড়ালেখা নাই')], max_length=500),
        ),
        migrations.AlterField(
            model_name='person',
            name='efficiency',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='t_novel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='t_poem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='t_story',
            field=models.IntegerField(default=0),
        ),
    ]
