# Generated by Django 4.2.4 on 2023-09-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_person_edu_qual_alter_person_efficiency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='depar_sub',
            new_name='depart_sub',
        ),
        migrations.RemoveField(
            model_name='person',
            name='tags_4',
        ),
    ]
