# Generated by Django 4.2.4 on 2023-09-06 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_rename_depar_sub_person_depart_sub_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='person',
            name='efficiency',
        ),
        migrations.RemoveField(
            model_name='person',
            name='t_novel',
        ),
        migrations.RemoveField(
            model_name='person',
            name='t_poem',
        ),
        migrations.RemoveField(
            model_name='person',
            name='t_story',
        ),
    ]
