# Generated by Django 4.2.4 on 2023-09-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='img_name',
            field=models.CharField(default=12, max_length=5000),
            preserve_default=False,
        ),
    ]
